keyword    = '''^(yield|function|async|await|extern|const|let|var|for|while)\b'''
identifier = '''^[A-Za-z_][A-Za-z0-9_]*'''
delimiters = '''^(\(|\)|\||\{|\}|\[|\]|;|:|,|<|>|\?|\#)'''
literal    = '''^(r\#\".*\"\#|\".*\"|[0-9]+)'''
types      = '''^([A-Z][A-Za-z0-9_]*|string|number|(?=: )[a-zA-Z][a-z_0-9A-Z])'''
extra      = '''^(==|!=|<=|>=|=|\+|-|\*|/|\.\.|=>)'''
function   = '''^([a-z][a-z_0-9]*)(?=\()'''
comment    = '''^(\/\/.*|/\*([\s\S]*?)\*/)'''
