keyword = '''^(crate|unsafe|extern|fn|cfg|super|let|mut|mod|pub|const|impl|static|for|use|dyn|while|match|if|else|break|continue|struct|enum|self)\b'''
identifier = '''^[A-Za-z_][A-Za-z0-9_]*'''
delimiters = '''^(\(|\)|\||\{|\}|\[|\]|;|:|,|<|>|\?|\#)'''
literal = '''^(r\#\".*\"\#|\".*\"|[0-9]+|[A-Z_]{3,})'''
types = '''^([A-Z][A-Za-z0-9_]*|str|[iu](8|16|32|64|size)|f(32|64)|\!|char|bool|(?=: )\w+)'''
extra = '''^(==|!=|<=|>=|=|\+|-|\*|/|\.\.|=>)'''
function = '''^([a-z][a-z_0-9]*)(?=\()'''
comment = '''^(\/\/.*|/\*([\s\S]*?)\*/)'''
