keyword     = "#cba6f7"
ident       = "#cdd6f4"
lit         = "#f9e2af"
delim       = "#6c7086"
types       = "#94e2d5"
extra       = "#89b4fa"
background  = "#1e1e2e"
function    = "#89b4fa"
comment     = "#6c7086"
