keyword     = "#c586c0" 
ident       = "#d4d4d4" 
lit         = "#ce9178" 
delim       = "#808080" 
types       = "#4ec9b0" 
extra       = "#569cd6" 
background  = "#1e1e1e" 
function    = "#9cdcfe"
comment     = "#6c7086"
