background = "#2B292D"   
comment    = "#655355"   
keyword    = "#FEB2C8"   
function   = "#FC976F"   
ident      = "#FECAAD"   
types      = "#D0D0E0"   
lit        = "#DBA49C"   
delim      = "#FECAAD"   
extra      = "#AAA497"   
accent     = "#A68978"   
# background = "#2B292D"   
# comment    = "#FECAAD"   
# keyword    = "#655355"   
# function   = "#FC976F"   
# ident      = "#FEB2C8"   
# types      = "#D0D0E0"   
# lit        = "#DBA49C"   
# delim      = "#956A60"   
# extra      = "#AAA497"   
# accent     = "#A68978"   
