keyword     = "#f6b6c9"   
ident       = "#f5d76e"   
lit         = "#ffa07a"   
delim       = "#6f5d63"   
types       = "#b1b695"   
extra       = "#d1d1e0"   
background  = "#2b292d"   
function    = "#ffa07a"   
comment     = "#383539"   
