keyword     = "#ff2eff" 
ident       = "#e0e0e0" 
lit         = "#00ff9f" 
delim       = "#888888" 
types       = "#00bfff" 
extra       = "#ffea00" 
background  = "#000000" 
function    = "#ff9100"
comment     = "#6c7086"
