keyword     = "#a0a0ff" 
ident       = "#c8c8c8" 
lit         = "#d2b48c" 
delim       = "#6f6f6f" 
types       = "#8fdac9" 
extra       = "#a4c2f4" 
background  = "#1a1a1d" 
function    = "#c6a0ff"
comment     = "#6c7086"
