keyword     = "#859900" 
ident       = "#839496" 
lit         = "#2aa198" 
delim       = "#586e75" 
types       = "#b58900" 
extra       = "#268bd2" 
background  = "#002b36" 
function    = "#cb4b16"
comment     = "#6c7086"
