keyword     = "#bb9af7"
ident       = "#c0caf5"
lit         = "#ff9e64"
delim       = "#565f89"
types       = "#2ac3de"
extra       = "#7dcfff"
background  = "#1a1b26"
function    = "#7aa2f7"
comment     = "#565f89"
