keyword     = "#ff7aa2" 
ident       = "#efefef" 
lit         = "#ffb86c" 
delim       = "#808080" 
types       = "#50fa7b" 
extra       = "#8be9fd" 
background  = "#1e1e28" 
function    = "#bd93f9"
comment     = "#6c7086"
